<?php
namespace App;
class Constants{
    const IN_CURSE = 'incourse';
    const FINISHED = 'finished';
    const FUTURE = 'future';
    const EQUAL='=';
    const ASC='asc';
    const DESC='desc';
    const STATUS='status';
    const MY_IN_CURSE = 'my_incurse';
    const MY_FINISHED = 'my_finished';
    const MY_FUTURE = 'my_future';
    const ACTIVE = '1';
    const INACTIVE = '0';
    const START='start';
    const MINUTES='minutes';
    const DATE_FORMAT= 'Y-m-d H:i:s';
    const AUCTIONS='auctions';
    const AUCTIONS_SELECT_ALL= 'auctions.*';
    const AUCTIONS_ID='auctions.id';
    const AUCTIONS_TYPE='auctions.type';
    const AUCTION_PRIVATE = 'private';
    const AUCTION_PUBLIC = 'public';
    const AUCTIONS_BATCH_ID='auctions.batch_id';
    const AUCTIONS_START='auctions.start';
    const AUCTIONS_END='auctions.end';
    const AUCTION_INV_AUCTION_ID='auctions_invites.auction_id';
    const AUCTION_PRICE_DECIMALS='AUCTION_PRICE_DECIMALS';
    const BATCHES='batches';
    const BATCH_ID='batches.id';
    const BATCH_ARRIVE_ID='batches.arrive_id';
    const ARRIVES='arrives';
    const ARRIVES_ID='arrives.id';
    const ARRIVES_BOAT_ID='arrives.boat_id';
    const BOATS='boats';
    const BOATS_ID='boats.id';
    const BOATS_USER_ID='boats.user_id';
    const USERS='users';
    const USERS_ID='users.id';
    const BIDS_DATE='bid_date';
    const BIDS_AUCTION_ID='bids.auction_id';
    const BIDS_USER_ID='bids.user_id';
    const PRODUCT='product';
    const PRODUCTS='products';
    const SELLER='seller';
    const SELLERS='sellers';
    const USER_RATING='userRating';
    const NOTIFICATION_STATUS_IN_CURSE = '0';
    const NOTIFICATION_STATUS_SENDING = '1';
    const NOTIFICATION_STATUS_SENDED = '2';
    const NO_CONCRETADA = 'noConcretized';
    const CONCRETADA = 'concretized';
    const PENDIENTE = 'pending';
    const CALIFICACION_POSITIVA = 'positive';
    const CALIFICACION_NEUTRAL = 'neutral';
    const CALIFICACION_NEGATIVA = 'negative';

}
