version: "3.4"

services:

  web:
    image: registry.netlabs.com.ar/netlabs/subastas
    environment:
      - DB_HOST=qa-subastas_db
      - DB_DATABASE=subastas
      - DB_USERNAME=root
      - DB_PASSWORD=sjkol343421xdsa!!
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=8UjkgIRwUCW1iVb8ylTtb56OXGKALoul
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - QUEUE_DRIVER=sync
      - MAIL_DRIVER=smtp
      - MAIL_HOST=190.210.73.141
      - MAIL_PORT=25
      - MAIL_USERNAME=alertas@netlabs.com.ar
      - MAIL_PASSWORD=4l3rt4s
      - MAIL_ENCRYPTION=null
      - MAIL_ADDRESS_SYSTEM=sistema@subastas.com.ar
      - MAIL_ADDRESS_SYSTEM_NAME=Subastas
    networks:
      - frontend 
      - backend
    deploy:
      labels:
        traefik.frontend.rule: "Host:subastas.qa.netlabs.com.ar"
        traefik.port: 80
        traefik.docker.network: frontend

  db:
    image: mysql:5.7.22
    command: mysqld --ignore-db-dir=lost+found
    environment:
      - MYSQL_ROOT_PASSWORD=sjkol343421xdsa!!
    networks:
      - backend
    volumes:
      - data:/var/lib/mysql
    deploy:
      labels:
        traefik.enable: "false"

  deploy:
    image: registry.netlabs.com.ar/netlabs/subastas_deploy
    environment:
      - DB_HOST=qa-subastas_db
      - DB_DATABASE=subastas
      - DB_USERNAME=root
      - DB_PASSWORD=sjkol343421xdsa!!
      - SUBJECT="qa deploy subastas"
    networks:
      - backend
    deploy:
      restart_policy:
        condition: none
      labels:
        traefik.enable: "false"


networks:
  frontend:
    external: true
  backend:
    

volumes:
  data: 
    driver: "vsphere"
    driver_opts:
      size: 8gb


